/* Generated by Together */

#include <TSystem.h>

#include "FairGeoLoader.h"
#include "FairGeoInterface.h"

#include "SpdCaveGeoTest.h"

ClassImp(SpdCaveGeoTest)

void SpdCaveGeoTest::ConstructGeometry()
{
  FairGeoLoader* loader = new FairGeoLoader("TGeo","Geo Loader");
  FairGeoInterface* GeoInterface =loader->getGeoInterface();
  
  GeoInterface->setMediaFile(TString(gSystem->Getenv("VMCWORKDIR"))+"/geometry/media.geo"); 
  GeoInterface->readMedia(); 
   
  //FairGeoCave* MGeo = new FairGeoCave();
  //MGeo->setGeomFile(GetGeometryFileName());
  //GeoInterface->addGeoModule(MGeo);
  //Bool_t rc = GeoInterface->readSet(MGeo);
  //if ( rc ) { MGeo->create(loader->getGeoBuilder()); }
}

